// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Products Service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "Get all products",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All products list",
            "schema": {
              "$ref": "#/definitions/ProductsResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "Get product by id",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Product description",
            "schema": {
              "$ref": "#/definitions/ProductResponse"
            }
          },
          "404": {
            "description": "Product not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "\"id\"": {
          "title": "Product.\"id\"",
          "type": "string"
        },
        "\"count\"": {
          "title": "Product.\"count\"",
          "type": "number"
        },
        "\"price\"": {
          "title": "Product.\"price\"",
          "type": "number"
        },
        "\"title\"": {
          "title": "Product.\"title\"",
          "type": "string"
        },
        "\"description\"": {
          "title": "Product.\"description\"",
          "type": "string"
        }
      },
      "required": [
        "\"id\"",
        "\"count\"",
        "\"price\"",
        "\"title\"",
        "\"description\""
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductsResponse": {
      "properties": {
        "products": {
          "items": {
            "$ref": "#/definitions/Product",
            "title": "ProductsResponse.products.[]"
          },
          "title": "ProductsResponse.products",
          "type": "array"
        }
      },
      "required": [
        "products"
      ],
      "additionalProperties": false,
      "title": "ProductsResponse",
      "type": "object"
    },
    "ProductResponse": {
      "properties": {
        "product": {
          "$ref": "#/definitions/Product",
          "title": "ProductResponse.product"
        }
      },
      "required": [
        "product"
      ],
      "additionalProperties": false,
      "title": "ProductResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "host": "my8qpq3fv2.execute-api.us-east-1.amazonaws.com/dev",
  "schemes": [
    "https"
  ]
};